---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      run: hello-mysql
  template:
    metadata:
      name: hello-mysql
      labels:
        run: hello-mysql
    spec:
      containers:
      - name: mysql-container
        image: saptarshi2446/mysqlnginx2:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service 
metadata:
  name: nginx-svc
  labels:
    run: hello-mysql
spec:
  selector:
    run: hello-mysql
  type: NodePort
  ports:
  - nodePort: 32266
    port: 83
    targetPort: 88
